controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
graphiql:
    path: /docs/graphiql
    controller: api_platform.graphql.action.graphiql